//! F1 完整功能字典與即時過濾資料庫。

use super::super::*;
use super::types::{HelpAction, HelpEntry, help_entry};

/// 依照搜尋條件過濾 F1 功能面板的完整資料。
pub(crate) fn help_entries(query: &str) -> Vec<HelpEntry> {
    let entries = vec![
        help_entry(
            ":rename",
            "r",
            "重新命名目前選取的檔案或資料夾",
            HelpAction::Command("rename"),
        ),
        help_entry(
            ":rename-regex",
            "R",
            "對目前選取或標記項目建立 regex 批次改名預覽；也可使用 :reg，預覽顯示 ready 才能套用",
            HelpAction::Command("rename-regex"),
        ),
        help_entry(
            ":create",
            "a",
            "建立新檔案、資料夾或巢狀路徑",
            HelpAction::Command("create"),
        ),
        help_entry(
            ":jump",
            "z",
            "用 fzf 遞迴掃描目前 panel 的目錄樹，快速挑選檔案或資料夾後直接跳過去",
            HelpAction::Command("jump"),
        ),
        help_entry(
            ":zoxide",
            "Z",
            "打開 zoxide 目錄列表，依照常用頻率快速跳到歷史工作目錄",
            HelpAction::Command("zoxide"),
        ),
        help_entry(
            ":goto <path>",
            "gt",
            "讓目前 panel 直接跳到指定路徑，支援相對路徑、絕對路徑、Windows 磁碟機路徑、UNC (// 或 \\\\) 與 smb:// share",
            HelpAction::Command("goto "),
        ),
        help_entry(
            ":goto document",
            "gd",
            "快速跳到 Documents 目錄",
            HelpAction::Command("goto ~/Documents"),
        ),
        help_entry(
            ":goto desktop",
            "gk",
            "快速跳到 Desktop 目錄 (desKtop)",
            HelpAction::Command("goto ~/Desktop"),
        ),
        help_entry(
            ":goto downloads",
            "gl",
            "快速跳到 Downloads 目錄 (downLoad)",
            HelpAction::Command("goto ~/Downloads"),
        ),
        help_entry(
            ":bookmark",
            "b",
            "打開書籤功能面板，可選擇自動儲存、列表跳轉、刪除單筆或清空全部書籤",
            HelpAction::Command("bookmark"),
        ),
        help_entry(
            ":diff",
            ":diff",
            "開啟全螢幕多 Panel 目錄矩陣與檔案內容差異比對 (N-Way Diff Matrix)",
            HelpAction::Command("diff"),
        ),
        help_entry(
            ":vdiff",
            "Ctrl+d",
            "切換目前選取檔案的版本控制差異預覽 (Git / SVN Unified Diff)",
            HelpAction::Command("vdiff"),
        ),
        help_entry(
            ":bookmark add",
            "ba",
            "自動挑選下一個可用代號，把目前 panel 的位置存成書籤",
            HelpAction::Command("bookmark add"),
        ),
        help_entry(
            ":bookmark jump",
            "bg/'{key}",
            "用列表挑選要跳去的書籤，或直接用單鍵快速跳轉",
            HelpAction::Command("bookmark jump"),
        ),
        help_entry(
            ":bookmark list",
            "bg",
            "列出目前可用的書籤清單，Enter 或 l 直接跳過去",
            HelpAction::Command("bookmark list"),
        ),
        help_entry(
            ":bookmark delete",
            "bd",
            "打開書籤刪除列表，可按對應按鍵或 Enter 刪除單筆書籤",
            HelpAction::Command("bookmark delete"),
        ),
        help_entry(
            ":bookmark clear",
            "bD",
            "直接刪除全部書籤",
            HelpAction::Command("bookmark clear"),
        ),
        help_entry(
            ":linemode",
            "m",
            "打開 linemode 面板，改變列表右側欄位顯示；目前支援 size、permissions、btime、mtime、none",
            HelpAction::Command("linemode "),
        ),
        help_entry(
            ":linemode size",
            "ms",
            "將列表右側欄位切成 size；資料夾在背景遞迴計算真實容量，檔案顯示大小",
            HelpAction::Command("linemode size"),
        ),
        help_entry(
            ":linemode permissions",
            "mp",
            "將列表右側欄位切成 permissions 顯示",
            HelpAction::Command("linemode permissions"),
        ),
        help_entry(
            ":linemode btime",
            "mb",
            "將列表右側欄位切成 btime 顯示",
            HelpAction::Command("linemode btime"),
        ),
        help_entry(
            ":linemode mtime",
            "mt",
            "將列表右側欄位切成 mtime 顯示",
            HelpAction::Command("linemode mtime"),
        ),
        help_entry(
            ":linemode none",
            "mn",
            "關閉 linemode，回到由排序方式決定的右側欄位顯示",
            HelpAction::Command("linemode none"),
        ),
        help_entry(
            ":copy",
            "y",
            "複製目前選取項目到內部剪貼簿",
            HelpAction::Command("copy"),
        ),
        help_entry(
            ":copy-picker",
            "c",
            "打開文字複製小視窗，可快速複製檔案路徑、目錄路徑、檔名或無副檔名檔名",
            HelpAction::Command("copy-picker"),
        ),
        help_entry(
            ":copy file-path",
            "cu",
            "打開 Copy 面板後複製目前項目的完整檔案路徑",
            HelpAction::Command("copy-picker"),
        ),
        help_entry(
            ":copy directory-path",
            "cd",
            "打開 Copy 面板後複製目前項目的所在目錄路徑；若本身是資料夾就複製該資料夾路徑",
            HelpAction::Command("copy-picker"),
        ),
        help_entry(
            ":copy filename",
            "cf",
            "打開 Copy 面板後只複製目前項目的檔名",
            HelpAction::Command("copy-picker"),
        ),
        help_entry(
            ":copy filename-without-extension",
            "cn",
            "打開 Copy 面板後複製去掉副檔名的檔名",
            HelpAction::Command("copy-picker"),
        ),
        help_entry(
            ":mark toggle",
            "Space",
            "切換目前游標所在項目的標記狀態，方便逐項多選",
            HelpAction::Command("mark-toggle"),
        ),
        help_entry(
            ":mark-all",
            "A",
            "把目前 panel 中所有可見的檔案與資料夾全部標記起來，方便批次操作",
            HelpAction::Command("mark-all"),
        ),
        help_entry(
            ":mark-invert",
            "Ctrl-r",
            "反轉目前 panel 所有可見項目的標記狀態",
            HelpAction::Command("mark-invert"),
        ),
        help_entry(
            ":unmark-all",
            "U",
            "清掉目前 panel 內所有已標記項目",
            HelpAction::Command("unmark-all"),
        ),
        help_entry(
            ":cut",
            "x",
            "剪下目前選取項目到內部剪貼簿",
            HelpAction::Command("cut"),
        ),
        help_entry(
            ":copy-panel",
            "yp / y1..9",
            "把目前選取或標記的項目複製到指定 panel 編號目前所在的目錄",
            HelpAction::Command("copy-panel "),
        ),
        help_entry(
            ":move <path>",
            "mm",
            "直接把目前選取或標記的項目移動到指定目錄",
            HelpAction::Command("move "),
        ),
        help_entry(
            ":move-panel",
            "mp / m1..9",
            "把目前選取或標記的項目移動到指定 panel 編號目前所在的目錄",
            HelpAction::Command("move-panel "),
        ),
        help_entry(
            ":linemode",
            "m",
            "打開 Move / LineMode 功能面板，支援搬移與檔案欄位顯示設定",
            HelpAction::Command("linemode"),
        ),
        help_entry(
            ":panel <id>",
            "1..9 / 0, Ctrl-p",
            "多 panel 時可直接按數字切換焦點；也可打開 panel 切換命令輸入指定編號",
            HelpAction::Command("panel "),
        ),
        help_entry(
            ":paste",
            "p",
            "貼上剪貼簿項目到目前目錄；若遇到同名項目，會先詢問是否整批覆蓋",
            HelpAction::Command("paste"),
        ),
        help_entry(
            ":paste!",
            "P",
            "貼上剪貼簿項目到目前目錄；若同名已存在就直接覆蓋，不會再詢問",
            HelpAction::Command("paste!"),
        ),
        help_entry(
            ":undo",
            "u",
            "復原最近一次完整 copy 或 move 批次；可連續執行，copy 建立物會移入 trash",
            HelpAction::Command("undo"),
        ),
        help_entry(
            ":cancel copied",
            "Y",
            "清掉目前內部剪貼簿中的 copy 狀態，不影響檔案本身",
            HelpAction::Command("cancel-copy"),
        ),
        help_entry(
            ":cancel cut",
            "X",
            "清掉目前內部剪貼簿中的 cut 狀態，不影響檔案本身",
            HelpAction::Command("cancel-cut"),
        ),
        help_entry(
            ":compress",
            "C",
            "把目前選取或標記的項目壓成 zip；多選時預設檔名為 archive.zip",
            HelpAction::Command("compress"),
        ),
        help_entry(
            ":extract",
            "E",
            "解開目前選取或標記的壓縮檔，支援 zip、tar.gz、tar、gz",
            HelpAction::Command("extract"),
        ),
        help_entry(
            ":open",
            "o/Enter",
            "用預設外部方式打開目前選取項目；文字檔走 $EDITOR，其他交給系統",
            HelpAction::Command("open"),
        ),
        help_entry(
            ":open-picker",
            "O/Shift-Enter",
            "打開 Open with 小視窗，手動選擇 Editor、Vim、Open 或 Reveal",
            HelpAction::Command("open-picker"),
        ),
        help_entry(
            ":vim",
            "",
            "直接用 vim 打開目前選取的檔案或目錄",
            HelpAction::Command("vim"),
        ),
        help_entry(
            ":reveal",
            "",
            "在系統檔案管理器中顯示目前選取的檔案或目錄",
            HelpAction::Command("reveal"),
        ),
        help_entry(
            ":delete",
            "d",
            "將目前選取項目移到 trash，並顯示確認提示",
            HelpAction::Delete,
        ),
        help_entry(
            ":delete!",
            "D",
            "永久刪除目前選取或標記項目，會先顯示確認提示",
            HelpAction::Command("delete!"),
        ),
        help_entry(
            ":trash",
            "tt",
            "打開 trash 面板，查看已移入 trash 的項目，並用 d/D/u/U 操作",
            HelpAction::Command("trash"),
        ),
        help_entry(
            ":tasks",
            "T",
            "打開目前 panel 的任務面板；支援 v 範圍選取、Space 標記、d/D 刪除與清空、x/X 取消任務",
            HelpAction::Command("tasks"),
        ),
        help_entry(
            ":status",
            "",
            "顯示 fd、fzf、rg、zoxide 是否已安裝並可從系統 PATH 使用",
            HelpAction::Command("status"),
        ),
        help_entry(
            ":update",
            "",
            "檢查 GitHub 最新版本並原地自動下載替換執行檔",
            HelpAction::Command("update"),
        ),
        help_entry(
            ":trash undo",
            "tu",
            "快速還原最近一次移到 trash 的檔案或資料夾",
            HelpAction::Command("trash undo"),
        ),
        help_entry(
            ":trash panel actions",
            "trash:d, trash:D, trash:u, trash:U",
            "在 trash 面板中刪除單筆、刪除全部、還原單筆或還原全部；都會先顯示確認視窗",
            HelpAction::Command("trash"),
        ),
        help_entry(
            ":search",
            "s",
            "用 fd 遞迴搜尋檔名與路徑；結果列表可按 f 做模糊過濾",
            HelpAction::Command("search"),
        ),
        help_entry(
            ":search-content",
            "S",
            "用 rg 遞迴搜尋檔案內容；結果列表可按 f 做模糊過濾",
            HelpAction::Command("search-content"),
        ),
        help_entry(
            ":preview-search",
            "/",
            "在 preview 內容中搜尋文字",
            HelpAction::Command("preview-search"),
        ),
        help_entry(
            ":preview",
            "Tab",
            "切換 preview mode；平常隱藏 preview，開啟後用整個 panel 顯示內容",
            HelpAction::Command("preview"),
        ),
        help_entry(
            ":split",
            "wj",
            "在目前 panel 下方建立新的 panel",
            HelpAction::Command("split"),
        ),
        help_entry(
            ":vsplit",
            "wl",
            "在目前 panel 右側建立新的 panel",
            HelpAction::Command("vsplit"),
        ),
        help_entry(
            ":split-up",
            "wk",
            "在目前 panel 上方建立新的 panel",
            HelpAction::Command("split-up"),
        ),
        help_entry(
            ":split-left",
            "wh",
            "在目前 panel 左側建立新的 panel",
            HelpAction::Command("split-left"),
        ),
        help_entry(
            ":close",
            "wc",
            "關閉目前 panel",
            HelpAction::Command("close"),
        ),
        help_entry(
            ":only",
            "wo",
            "只保留目前 panel",
            HelpAction::Command("only"),
        ),
        help_entry(
            ":terminal",
            "wt",
            "在 active panel 目前目錄開啟新終端；Windows 會繼承 PaneFM 的安全權杖與環境",
            HelpAction::Command("terminal"),
        ),
        help_entry(
            ":resize-mode",
            "wr",
            "進入視窗連續尺寸調整模式 (Sticky Resize Mode，hjkl/方向鍵微調)",
            HelpAction::Command("resize-mode"),
        ),
        help_entry(
            ":equal",
            "w=",
            "均等重設所有分割視窗大小 (Equalize)",
            HelpAction::Command("equal"),
        ),
        help_entry(
            ":width <+/-cols>",
            "wW",
            "調整目前視窗寬度（例如 :width +15 或 :width -10）",
            HelpAction::Command("width "),
        ),
        help_entry(
            ":height <+/-rows>",
            "wH",
            "調整目前視窗高度（例如 :height +5 或 :height -5）",
            HelpAction::Command("height "),
        ),
        help_entry(
            ":theme list",
            "tl",
            "打開主題列表；游標會停在目前使用中的主題",
            HelpAction::Command("theme list"),
        ),
        help_entry(
            ":theme next",
            "tn",
            "直接切到下一個主題",
            HelpAction::Command("theme next"),
        ),
        help_entry(
            ":help",
            "~/F1",
            "打開這個功能說明面板",
            HelpAction::Command("help"),
        ),
        help_entry(
            ":filter",
            "f",
            "開啟一般子字串過濾（可於輸入框按 Tab 切換模糊模式）",
            HelpAction::Filter,
        ),
        help_entry(
            ":filter fuzzy",
            "F",
            "開啟模糊搜尋過濾（Fuzzy filter，依相關性評分排序）",
            HelpAction::FuzzyFilter,
        ),
        help_entry(":sort", ",", "打開排序方式快捷鍵面板", HelpAction::Sort),
        help_entry(
            ":sort modified",
            ",m",
            "依修改時間正序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort modified reverse",
            ",M",
            "依修改時間倒序排序",
            HelpAction::Sort,
        ),
        help_entry(":sort birth", ",b", "依建立時間正序排序", HelpAction::Sort),
        help_entry(
            ":sort birth reverse",
            ",B",
            "依建立時間倒序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort alphabetical",
            ",a",
            "依字母順序正序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort alphabetical reverse",
            ",A",
            "依字母順序倒序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort natural",
            ",n",
            "依自然順序正序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort natural reverse",
            ",N",
            "依自然順序倒序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort extension",
            ",e",
            "依副檔名正序排序",
            HelpAction::Sort,
        ),
        help_entry(
            ":sort extension reverse",
            ",E",
            "依副檔名倒序排序",
            HelpAction::Sort,
        ),
        help_entry(":sort size", ",s", "依檔案大小正序排序", HelpAction::Sort),
        help_entry(
            ":sort size reverse",
            ",S",
            "依檔案大小倒序排序",
            HelpAction::Sort,
        ),
        help_entry(":sort random", ",r", "隨機排序目前列表", HelpAction::Sort),
        help_entry(":hidden", ".", "切換是否顯示隱藏檔", HelpAction::Hidden),
        help_entry(
            ":visual",
            "v",
            "進入視覺範圍標記模式，使用 j/k 移動，再按 v 或 Esc 結束",
            HelpAction::Visual,
        ),
        help_entry(
            ":quit",
            "q",
            "離開 terminal file manager",
            HelpAction::QuitHint,
        ),
    ];

    fuzzy_matched_indices_by_fields(&entries, query, |entry| {
        vec![
            entry.line.command.clone(),
            entry.line.shortcut.clone(),
            entry.line.description.clone(),
        ]
    })
    .into_iter()
    .map(|index| entries[index].clone())
    .collect()
}
